### ISSUE TITLE
Here's a question!

### ISSUE THREAD

**Issue by lambainsaan** [twolfson/AMA#1]
Hey Todd,

I saw your profile today while I was going through an issue on #Slack. You are a great Open Source Software Developer. I always wanted to be one, now I am in a college and this is the time when I might make good choices or the bad ones. 

I am from India and where I am studying Computer Science Engineering from is not a good college, they teach C++ 98 without any hands-on projects. The teachers here ask the students to memorize the algorithms instead of understanding them. They are 10-15 years behind this modern world.

I would say that the teachers here don't motivate us for programming. I want to be motivated about programming as I always wanted to make a useful piece of Software. But learning how to add 2 numbers on an old IDE for years won't help much.

 I will give you the background that I have.
1. I code in C++ and Java
2. I know basic web development 
3. I know basic algorithms (Trees , Linked List, etc..)
4. I know Git

I don't think so that I can go ahead and solve the bugs that Ruby have in their project by forking it right now. I want to get that good that I can push my commit to a famous open source project.

I never got a chance to ask this important question to anyone, today I saw that I could ask you anything.  
### What should I do to become a good open source software developer?

Thanks Todd! 

:smile:

**Comment by twolfson** [comment]
Hey @lambainsaan,
Thanks for the question. I'm sorry to hear about your teachers not educating nor motivating you =(

The main concepts that helped me get better at programming/open source were:
- Doing it more
- Being okay with ideas failing

Open source is one of the best utilities for exercising those concepts.

With respect to where to start, I typically solve a problem that I'm having and think would be useful to solve for other (e.g. slow workflow).

For example, my first projects were awfully written and poorly documented pieces of software but without them I wouldn't have started doing open source.

https://github.com/twolfson/Facebook-Scraper

https://github.com/twolfson/Resource-Collector

Eventually, you will start to think of more and more ideas to write about. Here's a list of ideas that I know I will never implement:

https://gist.github.com/twolfson/4109692

Once you are on a roll, then you can start to explore more things like:
- Writing tests and adding Continuous Integration (e.g. Travis CI)
- Writing/improving documentation
- Exploring other architectures
- Considering other languages for same job

I hope that has helped answer your question. Thanks again for asking =)

Sincerely,
Todd Wolfson
