### ISSUE TITLE
Why did you prefer not to move to NYC?

### ISSUE THREAD

**Issue by mmautner** [twolfson/AMA#2]
From your blogpost about leaving Underdog.io:

http://twolfson.com/2016-02-15-trying-something-new

**Comment by twolfson** [comment]
Thanks for your question! I'm originally from New Jersey and while I've never formally lived in NYC, I've had enough experience there that I'm confident that I wouldn't enjoy living there

For me, it's too fast paced, there's a lack of street friendliness, and I prefer snow-free climates
